import type { ModelSpec } from '@darshan/inference-core';

/**
 * YOLOv10n int8 ONNX export. Public, transformers.js-ready model on HuggingFace; ~2.6 MB on
 * the wire. YOLOv10 is end-to-end (NMS-free): the model outputs `[1, 300, 6]` where each row
 * is `[x1, y1, x2, y2, score, class_id]` in 640×640 input coordinates, pre-sorted by score
 * and zero-padded below the keep threshold. We previously shipped Xenova/yolov8n but that
 * repo is no longer publicly accessible.
 */
export const DETECTOR_YOLOV10N: ModelSpec = {
  id: 'onnx-community/yolov10n',
  task: 'object-detection',
  quantization: 'q8',
  files: [{ path: 'onnx/model_quantized.onnx', bytes: 2_650_737 }],
};

export const COCO_CLASSES = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
] as const;

export type CocoClass = (typeof COCO_CLASSES)[number];

/** Classes worth tracking for incident detection on driving footage. */
export const VEHICLE_CLASSES: ReadonlySet<CocoClass> = new Set<CocoClass>([
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'bus',
  'truck',
  'traffic light',
  'stop sign',
]);
